site_name: user_guide

nav:
  - PLATFORM: 
    - Getting Started: 'platform/10.md'
    - Applications & Modules:
      - Differences between Application and Modules: 'platform/20.md'
    - User and Companies: 'platform/30.md'
    - Authentication: 'platform/40.md'
    - CONNECT (Collaboration): 'platform/50.md'
    - Advance Settings: 'platform/60.md'
    - Languages: 'platform/70.md'
    
  # - FINANCE & ACCOUNTING: 
  #   - Getting Started: 'finance/10.md'
  #   - Account Receivable: 'finance/20.md'
  #   - Account Payable: 'finance/30.md'
  #   - Bank and Cash: 'finance/40.md'
  #   - Taxation: 'finance/50.md'
  #   - Analytic Accounting: 'finance/60.md'
  #   - Multi-Currencies: 'finance/70.md'   
  #   - Reporting: 'finance/80.md'  
  #   - Asset Management: 'finance/90.md'  
  #   - Budget Management: 'finance/100.md'  
  #   - Approval: 'finance/110.md'  

  # - SALES & MARKETING: 
  #   - Contact Management: 'finance/10.md'
  #   - Customer Relationship Management:
  #     - CRM Workflow: 'finance/20.md'
  #     - Activities in CRM: 'finance/20.md'
  #     - Orhanize the Pipeline: 'finance/20.md'
  #     - Acquire Leads: 'finance/20.md'
  #     - Assign and Track Leads: 'finance/20.md'
  #     - Analyze Performance: 'finance/20.md'
  #     - Optimize Day-to-Day operations: 'finance/20.md'
  #   - Sales Management:
  #     - Quotation: 'finance/20.md'
  #     - Pro-Forma Invoice: 'finance/20.md'      
  #     - Product Management:
  #       - Product Category: 'finance/20.md'
  #       - Product Attributes: 'finance/20.md'
  #       - Product Configurator: 'finance/20.md'
  #     - Invoicing:
  #       - Product and Taxes: 'finance/20.md' 
  #       - Shipping Cost: 'finance/20.md' 
  #     - Customer Payment:
  #       - Online Payment: 'finance/20.md'        
  #   - Pricing Management:
  #     - Pricing Strategies: 'finance/20.md'  
  #   - Promotion Management:
  #     - Promotion Program: 'finance/20.md'   
  #     - Coupon Program: 'finance/20.md'   
  #   - Commission Management:
  #     - Agents Program: 'finance/20.md'   
  #     - Commisison Configuration: 'finance/20.md'      
  #   - Email Marketing: 'finance/20.md'   
  #   - SMS Marketing: 'finance/20.md' 
  #   - Customer Survey: 'finance/20.md'     

  # - WAREHOUSE & INVENTORY:
  #     - Product Management:
  #       - Product Category: 'finance/20.md'
  #       - Product Attributes: 'finance/20.md'
  #       - Product Configurator: 'finance/20.md'
  #     - Vendor Management:
  #       - Optimize Day-to-Day operations: 'finance/20.md'
  #     - Purchase Management:
  #       - Purchase Agreement: 'finance/20.md'
  #       - Request for Quotation: 'finance/20.md'
  #       - Purchase Order: 'finance/20.md'
  #       - Receiving Products: 'finance/20.md'
  #       - Performance and Reporting: 'finance/20.md'
  #       - Vendor Bill: 'finance/20.md'
  #       - Vendor Payment: 'finance/20.md'
  #     - Warehouse Management:
  #       - Warehouses: 'finance/20.md'
  #       - Location: 'finance/20.md'
  #       - Planning: 'finance/20.md'
  #       - Rules and Routes: 'finance/20.md'
  #       - Incoming Shipment : 'finance/20.md'
  #       - Delivery Order: 'finance/20.md'
  #       - Shipping Operations: 'finance/20.md'
  #       - Miscellaneous Operations: 'finance/20.md'
  #       - Inventory Adjustment: 'finance/20.md'
  #     - Inventory Management:
  #       - Product Management: 'finance/20.md'
  #       - Unit of Measure: 'finance/20.md'
  #       - Product Packing: 'finance/20.md'
  #       - Product Traceability : 'finance/20.md'
  #       - Inventoru Operations: 'finance/20.md'
  #       - Inventory Adjustment: 'finance/20.md'
  #       - Scrap Management: 'finance/20.md'
  #       - Landed Cost: 'finance/20.md'

  # - HUMAN RESOURCES:
  #     - Employee Management: 'finance/20.md'
  #     - Attendance Management: 'finance/20.md'
  #     - Leave Management: 'finance/20.md'
  #     - Payroll Management: 'finance/20.md'
  #     - Expenses Management: 'finance/20.md'
  #     - Employee Appraisal: 'finance/20.md'
  #     - eLearning: 'finance/20.md'

  # - WEBSITE & ECOMMERCE:
  #     - Website Builder: 
  #       - Setting Up: 'finance/20.md'
  #       - Multiple Language: 'finance/20.md'
  #       - Search Enginer Optimization (SEO): 'finance/20.md'
  #       - Website Traffic Tracking: 'finance/20.md'
  #     - Selling Online: 
  #       - Planning: 'finance/20.md'    
  #       - Credit Card Payment: 'finance/20.md'   
  #       - Cross Selling Products: 'finance/20.md'    
  #     - Live Chat: 
  #       - Planning: 'finance/20.md'    

  # - MANUFACTURING AND PRODUCTION:
  #     - Planning: 'finance/20.md'
  #     - Manufacturing Management: 
  #       - Bill of Materials: 'finance/20.md'

  # - SUPPLY CHAIN AND LOGISTICS:
  #     - Planning: 'finance/20.md'

  # - CUSTOMER SERVICES:
  #     - Help Desk: 'finance/20.md'
  #     - Field Service: 'finance/20.md'
  #     - Project Management: 'finance/20.md'
  #     - Membership Management: 'finance/20.md'

  # - RETAIL BUSINESS:
  #     - Planning: 'finance/20.md'

  # - KNOWLEDGE AND DOCUMENTS:
  #     - Planning: 'finance/20.md'

